apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: docker.io/shayyo/web-application-redis:latest
    imagePullPolicy: Always
    #command: ['/bin/bash', '-c', '/usr/local/bin/entrypoint.sh']
    command: ['/usr/local/bin/entrypoint.sh']
      #command: ['redis-server', '/redis-master/redis.conf']
    env:
    - name: MASTER
      value: "true"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: example-redis-config
        items:
        - key: redis-config
          path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-redis-config
data:
  redis-config: |
    protected-mode no
